### ISSUE TITLE
Edit profile page - bug Major

### ISSUE THREAD

**Issue by vuongb2** [info442-su23/g-team#48]
None of the queries are functional // can't save changes

I would expect to be able to adjust the information if I click on a query and then save those changes

on windows chrome

![Edit-profile](https://github.com/info442-su23/g-team/assets/114948475/fb717a8d-1cf9-43f3-9345-c0d3f42dcb14)

**Comment by taylor-russon** [comment]
I was also having this issue using Chrome Version 115.0.5790.170 on macOS Monterey Version 12.5. I was able to change the gender and school year, but only if I clicked on the tiny arrow to the right. However when I clicked "Save Changes" nothing happened.

**Comment by ericagordy** [comment]
I am also on chrome. I was only able to change the school year. nothing happens when i click save changes.

**Comment by jasmpa-1777547** [comment]
Uploading profile picture works, entering major, and changing gender/sex works. However, users must click on the "upload profile picture" button multiple times in order to upload their picture. Additionally, users can't view their saved changes (this will be fixed).

**Comment by kchoi22** [comment]
issue fixed, even if the user doesn't add a new profile picture, they can now update their profile and see the pop-up message after the submission.
