### ISSUE TITLE
3x Feature request - Empty states, Navigation issues, and expanding posts

### ISSUE THREAD

**Issue by vuongb2** [info442-su23/g-team#49]
It would be pleasant if on the friends list page, the "your friends" and "suggested friends" had an empty state and/or call to action to make the page more "full". See empty states at (https://www.useronboard.com/onboarding-ux-patterns/empty-states/). 
Another feature that would be nice is if after clicking on a friend to chat with, you could navigate between other chats you have with other friends. For example, when I open my chat with Kevin I can't switch to the chat with Kchoi from the friends online list.
Some small quick fixes might be to label the @my username account tag or get rid of it entirely since it's a bit confusing, and to somehow make it more clear that posts on the forum are actually expandable but only if you click the title.

![image](https://github.com/info442-su23/g-team/assets/114948475/937a2694-1917-4a15-ae33-7baf01375aef)
![image](https://github.com/info442-su23/g-team/assets/114948475/4e9770e9-ed95-45b6-a7dc-75b63a7042df)

**Comment by jasmpa-1777547** [comment]
Will incorporate this feature into the next sprint, we also think it would be a good idea for empty states, fixing navigation issues, and expanding the posts.

**Comment by kchoi22** [comment]
Added empty state for current friend-list, fixed navigation issues, and changed styling for the posts.
