### ISSUE TITLE
Deleted Post (bug minor + feature request)

### ISSUE THREAD

**Issue by sjhu2020** [info442-su23/g-team#50]
<img width="964" alt="image" src="https://github.com/info442-su23/g-team/assets/74697916/422552e0-ed81-42aa-b0d3-c4076ea88cc7">
There is a deleted post that is always present at the top of the home page.  I expected it to go away if I refreshed the page or searched for something but it didn't after doing these things.  My suggestion is that because it doesn't give any useful information, deleted posts should just get removed from the home page.  Also, I could not find a way to delete a post I had created, this seems like an important feature that is either buggy or not present.

**Comment by jasmpa-1777547** [comment]
Decided to state as "bug minor". The deleted post that appears on the homepage was hard-coded in the application and can be easily removed. However, adding the new feature of deleting a post that a user has created cannot be implemented in the next sprint as there is not enough time to do so.

**Comment by kchoi22** [comment]
Since we decided that we do not have the time to fully incorporate a fully functional "delete/edit" post feature until the next sprint we decided to remove the delete post feature from our website to fix the following issue.
