### ISSUE TITLE
Request a Walking Buddy- Bug Minor

### ISSUE THREAD

**Issue by BrookePedersen** [info442-su23/g-team#51]
Bug: minor
General summary of the problem: once ride is requested, nothing happens
Steps to reproduce: display a pop-up of some sort to show the user confirmation of their request.
Expected result: some sort of confirmation page or message to let me know it went through
Actual result: page just refreshed

<img width="1440" alt="Screen Shot 2023-08-08 at 5 28 32 PM" src="https://github.com/info442-su23/g-team/assets/84031057/0de6aa88-9c53-4a6e-9ef6-42a3bca3e451">
<img width="1438" alt="Screen Shot 2023-08-08 at 5 28 42 PM" src="https://github.com/info442-su23/g-team/assets/84031057/4415b2af-4560-4f3a-b6c8-705673b08df8">

**Comment by jasmpa-1777547** [comment]
Bug minor verified, will incorporate a pop-up when users click on the request button to notify them of refreshing the page to see their request posted or having the page refresh by itself once the user presses the request button.

**Comment by kchoi22** [comment]
Fixed the issue by adding a pop-up when the user successfully submits the form and once the pop-up is closed, the page will reload by itself, and user's request will be added to the buddy request box.
