### ISSUE TITLE
Feature Request (Implement a mobile first design)

### ISSUE THREAD

**Issue by Mustafabd** [info442-su23/g-team#53]
- When I try to resize the page that we enter after logging in, the test starts to misalign
- Fixing this will help keep your webpage neat and look more professional
<img width="105" alt="image" src="https://github.com/info442-su23/g-team/assets/80429899/97d56f01-1249-445e-9f43-5b719449a36d">

**Comment by jasmpa-1777547** [comment]
Decided: "feature request" and we will be incorporating a more accessible application on other devices.

**Comment by kchoi22** [comment]
Added media query to the styling sheet for the app to have more mobile friendly layout.
