### ISSUE TITLE
Find password feature not working (Bug major)

### ISSUE THREAD

**Issue by FastFusion5** [info442-su23/g-team#56]
I created an account using my email address, then I was directed back to the login page. When I was testing out the forgot password, I was given the error message: "Error sending password reset email. Please try again later." Not sure if this is just me or a general occurrence. I am running Safari 16.3 on MacBook Pro.
<img width="728" alt="Screenshot 2023-08-09 at 8 35 58 AM" src="https://github.com/info442-su23/g-team/assets/77070825/f0f3033d-328e-4df0-9313-db7600cc62a6">

**Comment by jasmpa-1777547** [comment]
Tested and verified that the forgot password does work. User can input their email and will receive mail immediately to reset their password.
