### ISSUE TITLE
navigation bar (feature request)

### ISSUE THREAD

**Issue by Zuoooooo** [info442-su23/g-team#57]
A logo in the upper left corner of the homepage can have a more unique character than just a logo. When the user clicks the logo in the upper left corner of the website, they can also jump to the homepage.

**Comment by Zuoooooo** [comment]
<img width="119" alt="Screen Shot 2023-08-08 at 5 40 51 PM" src="https://github.com/info442-su23/g-team/assets/114701960/ea5fdc96-90b2-4ba5-9c4c-c098a3dd08df">

**Comment by jasmpa-1777547** [comment]
Decided on "wontfix" as there is already a "Home" tab for users to click on.
