### ISSUE TITLE
Major Bug: Notifications don't actually link up 

### ISSUE THREAD

**Issue by sloaneshea** [info442-su23/g-team#58]
1. Major Bug
2. When in settings and clicked the check to allow notifications, nothing changes
3. Chrome Version 115.0.5790.114 (Official Build) (x86_64)
4. settings, enable notifications
5. Notifications or some sort of browser pop up that confirms the request
6. Nothin
7. 
<img width="918" alt="Screen Shot 2023-08-08 at 8 41 19 PM" src="https://github.com/info442-su23/g-team/assets/77075019/ae5368ec-98da-41b6-9a1b-ed246846e9a8">

**Comment by jasmpa-1777547** [comment]
Decided on "bug minor" as a pop-up indicating that the user wants to enable notifications can be easily implemented.

**Comment by kchoi22** [comment]
Added a browser notification indicating that the user enabled the notifications when the "notification" check-box is checked.
