### ISSUE TITLE
Major : Online friends are not clickable 

### ISSUE THREAD

**Issue by haonanzzz** [info442-su23/g-team#59]

**Comment by haonanzzz** [comment]
- Online friends are not clickable on all pages
- major
- The clickabilities of the online friends' individuals and pages are inconsistent: in same page, some of the friend can be clickable for chatting; in another page, none of the friend can be clicked for chatting
- Microsoft edge on win 11
- In the home page, friend KEVIN can be clicked, while kchoi22 cannot. In the different page rendered through 'Request a walking buddy', both of them are not able to clicked.
- Expect to be clickable for all online friends and start chat
- Actual results: not consistent clickabilities which lead confusions and inconvenience

**Comment by jasmpa-1777547** [comment]
Tested and bug was verified. Clicking on friend's names to message them only works on the homepage but not on the friend's list page. Will fix this bug so that each friend name can be clickable on any page.

**Comment by kchoi22** [comment]
Issue fixed, now online-friends name can be clicked on any pages of the website.
