### ISSUE TITLE
Minor Feature: The links in the footer, Contact Us, Terms, and Privacy, are not clickable

### ISSUE THREAD

**Issue by ryo884-2177391** [info442-su23/g-team#61]
I really applicate your project idea because we students need this web service for the security concern on campus.
One thing that I found is these links in the footer are not clickable, and am confused whether these are supposed to be clickable or not. Since the underlines are attached to each of them, we users can easily guess that we could have clicked them.

**Comment by jasmpa-1777547** [comment]
Decided on "wontfix". Although the suggestion is great, these changes might not be ready on time for the next sprint and are not as necessary for the functionality of our application.
