### ISSUE TITLE
Cannot access any of these links at bottom of sign-in page including other recovery account options (Minor Bug)

### ISSUE THREAD

**Issue by bonglrob** [info442-su23/g-team#62]
Expected: To click on a link to go to recovery account options page
Actual: Unclickable

Env: Brave Browser/Chrome v1.56.20/ Acer Windows 11 Desktop

![brave_ZpZU1hZyQW](https://github.com/info442-su23/g-team/assets/8757841/5bed1efd-f816-417c-8d99-96b14443c06d)

**Comment by jasmpa-1777547** [comment]
Decided on "wontfix". Changes won't be implemented on time for the next sprint.
