### ISSUE TITLE
Feature Request - Searching for friends format

### ISSUE THREAD

**Issue by syd-moral** [info442-su23/g-team#63]
spacing out the suggested friends when typing into the search bar on the friends list page would help increase accessibility, and would also just look a lot better.

**Comment by jasmpa-1777547** [comment]
Labeled: "feature request". Will be implementing this change into the next sprint.

**Comment by kchoi22** [comment]
Fixed the issue by changing the search result style. Now the results are much more spaced out, less space-taking, and neater.
