### ISSUE TITLE
Cannot create account; No alternative way; Severity: Major

### ISSUE THREAD

**Issue by MarinaCui** [info442-su23/g-team#65]
Summary: cannot create account using my email, and there is no alternative way to create 
Environment: Chrome 115.0.5790.170 on macOS Ventura 13.4
Steps to Reproduce: Sign Up Page -> Enter credentials -> Click on Create account -> Firebase Error
Expected Result: Provide Additional Sign up method if necessary
Actual Result: Firebase Error

**Comment by jasmpa-1777547** [comment]
Tested and verified on the same environment, and did not verify this bug. Creating account with email works.
