### ISSUE TITLE
Complete Buddy Request - Feature Request

### ISSUE THREAD

**Issue by elisabeth-h7** [info442-su23/g-team#66]
I think it would be helpful to include a way to accept a buddy request so the user can find someone to walk home with. Or if it's meant for people to just go meet with them if they see the request maybe include that in a description at the top of the page. I think this would be helpful because right now there are just a list of buddy requests, but no way to know if someone is completing them or if people still need a walking buddy.

**Comment by jasmpa-1777547** [comment]
Decided on "wontfix". This suggestion is great, however, users can click on the post to be directed to messaging the original poster to verify if they still need a walking buddy. Additionally, this change might not be completed on time for the next sprint.
