### ISSUE TITLE
Feature request: Page query

### ISSUE THREAD

**Issue by VictoriaVVei** [info442-su23/g-team#68]
Description of the requested feature: It would be clean to have a page query, and set number limit.

Why: After I open Friends List, there will be a very long list to load, which is redundant.

Attachments: 
Your website: 
![9caecf3af5037847967931ec385cfe5](https://github.com/info442-su23/g-team/assets/91993339/33aa6421-74a4-47bd-8b91-41f7039aea61)

Example:
https://space.bilibili.com/24476098/fans/follow

**Comment by jasmpa-1777547** [comment]
Labeled "feature request". Will incorporate a scrollable feature with the friends list so that the page doesn't become a long list.

**Comment by kchoi22** [comment]
After working with the code, noticed that even with the scrollable feature the suggested-friend list looks a bit lengthly. Therefore, fixed the issue by setting the max length of the suggested friend to 5. If the user adds a friend from the suggested-friend list, a new friend will be added to the list, and the user will always have 5 suggested-friends.
