### ISSUE TITLE
Minor bug: Friends List will all overlap together when serching

### ISSUE THREAD

**Issue by VictoriaVVei** [info442-su23/g-team#69]
Summary: Friends List will all overlap together when serching
Environment: Chrome on Win 11 (Version 115.0.5790.171)
Steps to reproduce: After input something inside the search area, all the list will overlapping together
Expected result: Contents inside the list keep seperate
Actual result: Contents inside the list keep seperate all overlap
Attachments:
![f67951533a3a33b68a4c2b7e203f280](https://github.com/info442-su23/g-team/assets/91993339/82c097d2-ca0f-4309-a0d4-5f242aa1512e)

**Comment by jasmpa-1777547** [comment]
Tested the bug and verified. Will change the styling of the results so that they won't overlap.

**Comment by kchoi22** [comment]
Fixed the overlap by changing the style of the search results.
