### ISSUE TITLE
Implement a filter button for posts and remove deleted posts (feature request) 

### ISSUE THREAD

**Issue by luckypanda88** [info442-su23/g-team#70]
- I think it would be nice to have a filter button where users can filter the posts by date or by user
- Removing deleted posts from UW Get Home Safe Community Forum or bring those deleted posts to the very bottom of the forum. 
- This can be helpful for users to view information quickly and efficiently.

**Comment by jasmpa-1777547** [comment]
Duplicate post. Will not be implementing these changes as they might not be added on time for the next sprint.
