### ISSUE TITLE
Major -- Messaging feature doesn't allow for any user input.

### ISSUE THREAD

**Issue by EloraHob** [info442-su23/g-team#71]
Clicking 'Message' button on user profile page reveals a moveable Message popup, but no way to interact further-- unable to draft a message, and there is no error or indication of what can/can't be done in this popup.

**Comment by jasmpa-1777547** [comment]
Tested bug and did not verify. User can send messages and click on chat history with the people they have sent messages to.

**Comment by EloraHob** [comment]
Apologies, this report was meant for a different group
